In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from scipy.stats import pearsonr

In [3]:
path = os.getcwd() + "\Datasets\\"
print(os.listdir())
df = pd.read_csv("Indicator.csv")
df.head(10)

['.git', '.ipynb_checkpoints', 'Datasets', 'Gini_Index.ipynb', 'Indicator.csv', 'Pop_Growth.ipynb', 'README.md']

      Indicator_Code                                     Indicator_Name
0        SP.POP.GROW                           Population Growth (in %)
1        SI.POV.GINI                                         Gini Index
2  NY.GDP.PCAP.KD.ZG                       GDP per capita growth (in %)
3  SE.XPD.TOTL.GB.ZS  Government expenditure on education, total (% ...
4  SE.XPD.TOTL.GD.ZS  Government expenditure on education, total (% ...
5     SI.DST.FRST.10                    Income share held by lowest 10%
6     SI.DST.10TH.10                   Income share held by highest 10%
7  SL.UEM.TOTL.NE.ZS  Unemployment, total (% of labour force) (natio...
8     SP.DYN.CBRT.IN                Birth Rate, crude (per 1000 people)
9     SP.DYN.CDRT.IN                Death Rate, crude (per 1000 people)

In [4]:
indicator_csvs = [path + i for i in df.Indicator_Code]
df1 = ["\\".join(i.split("\\")) for i in indicator_csvs]
#print(df1)
#To get the Gini Index CSV
giniIndex = pd.read_csv(df1[1] + "\\" + os.listdir(df1[1])[0])#, sep='delimiter',header=None)#, error_bad_lines=False)

In [5]:
giniIndex.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.3,NaN
3,Albania,ALB,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29.0,NaN,34.6,32.9,33.7,33.2,NaN,NaN
4,Andorra,AND,Gini index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN